spring:
  application:
    name: person_service
  datasource:
    url: jdbc:postgresql://localhost:5432/ddd-db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop